spring.application.name=backend

# Aiven Cloud Database Connection
spring.datasource.url=jdbc:mysql://mysql-184984b-sanjeevani.h.aivencloud.com:14330/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ft7_qJr4JpDKkg0hy6D
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
gemini.api.key=AIzaSyA_lACqVa5Zghg2lJbX6vzf9Ldq1CfBkbU
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=